### ISSUE TITLE
canvasxpress isn't listed as a dependency

### ISSUE THREAD

**Issue by sammyjava** [neuhausi/canvasxpress-react#2]
`npm i canvasxpress-react` doesn't install canvasxpress as a dependency.

**Comment by neuhausi** [comment]
npm install canvasxpress-react --save

**Comment by sammyjava** [comment]
```
$ npm install canvasxpress-react --save

added 1 package, and audited 1449 packages in 2s
```
Note 1 package, not two.

```
$ grep canvasxpress package-lock.json 
        "canvasxpress-react": "^40.4.114",
    "node_modules/canvasxpress-react": {
      "resolved": "https://registry.npmjs.org/canvasxpress-react/-/canvasxpress-react-40.4.114.tgz",
    "canvasxpress-react": {
      "resolved": "https://registry.npmjs.org/canvasxpress-react/-/canvasxpress-react-40.4.114.tgz",
$
```

```
$ grep canvasxpress package.json 
    "canvasxpress-react": "^40.4.114",
$
``` 
```
$ npm install canvasxpress --save

added 1 package, and audited 1450 packages in 3s
```

Now it's been added.

**Comment by neuhausi** [comment]
Oh. Do you mean I should add CanvasXpress in the json.package?

**Comment by sammyjava** [comment]
Yeah, as a dependency. It's called from canvasxpress-react. Not a big deal, but thought I'd mention it. node modules are supposed to include all of their dependencies.

**Comment by sammyjava** [comment]
Oh, crypto as well, in the canvasxpress module. :)
```
Module not found: Error: Can't resolve 'crypto' in '/home/shokin/react-canvasxpress/node_modules/canvasxpress/src'
```

**Comment by neuhausi** [comment]
I thought that was part of the browser

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sammyjava** [comment]
Yeah that was my mistake, I deleted the comment.

**Comment by neuhausi** [comment]
Are you set until the next release?

**Comment by sammyjava** [comment]
I got stuff to work in the create-react-app environment, but right now in the InterMine bluegenes setup I'm struggling with the following which is thrown from a css in canvasexpress module:
```
Uncaught Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @charset "UTF-8";
```
I presume I have to tweak webpack in some way, but so far I'm striking out. I expect I'll figure it out. I don't want to edit your module and I know it works in the create-react-app enviro.

**Comment by sammyjava** [comment]
This is the top line for the above trace. Some webpack loader issue.
`webpack://canvasXpressTest/./node_modules/canvasxpress/src/canvasXpress.css?:1`

**Comment by neuhausi** [comment]
Let me know if you want me to make a change.

**Comment by sammyjava** [comment]
I figured out the webpack problem. I needed to install an old version of css-loader 5.2.7 to work with the older webpack this setup uses, and had to add this to the rules in webpack.config.js:
```
            {
                test: /\.s?[ac]ss$/,
                use: {
                    loader: "css-loader"
                }
            }
```

**Comment by neuhausi** [comment]
Perfect. Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
