### ISSUE TITLE
v41.0.9 throwing Uncaught ReferenceError: CanvasXpress is not defined

### ISSUE THREAD

**Issue by sammyjava** [neuhausi/canvasxpress-react#4]
I updated canvasxpress-react and canvasxpress to 41.0.9 from npm, and now I'm getting

"Uncaught ReferenceError: CanvasXpress is not defined" in this line:
```
CanvasXpress = CanvasXpress.ready ? CanvasXpress : function (j, f, e, o, d, k, g, n, m, i) {
```
which is line 312 in canvasXpress.js. 

This problem is not present if I run both canvasxpress and canvasxpress-react 40.4.114. If either is 41.0.9 I get the error.

**Comment by neuhausi** [comment]
Ooops! I will fix in the next version

**Comment by neuhausi** [comment]
Hi Sam,
I just released version 41.1. Can you please check and close this issue if it is fixed :-)
Thank you

**Comment by sammyjava** [comment]
Thanks, but unfortunately still broken. I tested 41.1.4. Here's my repo for testing, `npm install; npm start` to see. I've got the working version 40.4.114 in package.json. I `rm -r node_modules; npm install; npm start` after changing the version, just in case.

https://github.com/sammyjava/react-canvasxpress

But I'm happy to do the testing.

**Comment by neuhausi** [comment]
Thank you Sam. I believe I have a fix. Let me check and put it in the next version

**Comment by neuhausi** [comment]
Check Version 41.2.6. It is fixed!
Please close the issue after testing.
Thank you.

**Comment by sammyjava** [comment]
Indeed! Thanks, Isaac!!
